class 1

In [16]:
import statistics
ages = [19, 22, 21, 35, 28, 24, 31, 19, 27, 40]

In [17]:
mean_age = statistics.mean(ages)
median_age = statistics.median(ages)

In [18]:
print("a)Length =",len(ages))
print("b)Total =",sum(ages))
print("c)Mean =",mean_age)
print("d)Minimum =",min(ages))
print("  Minimum =",max(ages))
print("e)Median =",median_age)
print("When mean and median disagree, it means data values are unevenly distributed.")

a)Length = 10
b)Total = 266
c)Mean = 26.6
d)Minimum = 19
  Minimum = 40
e)Median = 25.5
When mean and median disagree, it means data values are unevenly distributed.

class 2

In [11]:
import pandas as pd
df = pd.read_csv("C:/Users/HP/OneDrive/Desktop/JUPYTER/50_startups.csv")
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [13]:
s = df["Profit"] # Series
d = df[["Profit"]] # DataFrame
print(type(s)), print(type(d))
print(s.shape, d.shape)

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
(50,) (50, 1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [15]:
df.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

class 3

In [22]:
df = pd.read_excel("C:/Users/HP/OneDrive/Desktop/JUPYTER/50_startups_messy.xlsx")
print(df.shape) # size
print(df.isnull().sum()) # completeness
print(df.duplicated().sum()) # uniqueness

(50, 5)
R&D Spend          0
Administration     0
Marketing Spend    1
State              0
Profit             0
dtype: int64
0

In [25]:
df = df.drop_duplicates()
df["Marketing Spend"] = df["Marketing Spend"].str.strip().str.title()
df["Marketing Spend" ] = pd.to_numeric(df["Marketing Spend"], 
errors="coerce")

In [29]:
random_sample = df.sample(20, random_state=7)

stratified_sample = df.groupby("State").sample(frac=0.2, random_state=7)

print(random_sample)

    R&D Spend  Administration  Marketing Spend       State     Profit
13   91992.39       135495.07              NaN  California  134307.35
15  114523.61       122616.84              NaN    New York  129917.04
22   73994.56       122782.75              NaN     Florida  110352.25
42   23640.93        96189.63              NaN  California   71498.49
30   61994.48       115641.28              NaN     Florida   99937.59
27   72107.60       127864.55              NaN    New York  105008.31
1   162597.70       151377.59              NaN  California  191792.06
20   76253.86       113867.30              NaN  California  118474.03
10  101913.08       110594.11              NaN     Florida  146121.95
36   28663.76       127056.21              NaN     Florida   90708.19
32   63408.86       129219.61              NaN  California   97427.84
46    1315.46       115816.21              NaN     Florida   49490.75
34   46426.07       157693.92              NaN  California   96712.80
18   91749.16       114175.79              NaN     Florida  124266.90
17   94657.16       145077.58              NaN    new york  125370.37
35   46014.02        85047.44              NaN    New York   96479.51
29   65605.48       153032.06              NaN    New York  101004.64
41   27892.92        84710.77              NaN     Florida   77798.83
9   123334.88       108679.17              NaN  California  149759.96
2   153441.51       101145.55              NaN     Florida  191050.39

In [30]:
print("Population:")
print(df[["R&D Spend", "Marketing Spend"]].mean())

print("\nRandom Sample:")
print(random_sample[["R&D Spend", "Marketing Spend"]].mean())

print("\nStratified Sample:")
print(stratified_sample[["R&D Spend", "Marketing Spend"]].mean())

Population:
R&D Spend          73721.6156
Marketing Spend           NaN
dtype: float64

Random Sample:
R&D Spend          76076.3745
Marketing Spend           NaN
dtype: float64

Stratified Sample:
R&D Spend          55550.343333
Marketing Spend             NaN
dtype: float64

In [31]:
print("Random sample difference:")
print((random_sample[["R&D Spend", "Marketing Spend"]].mean()
       - df[["R&D Spend", "Marketing Spend"]].mean()).abs())

print("Stratified sample difference:")
print((stratified_sample[["R&D Spend", "Marketing Spend"]].mean()
       - df[["R&D Spend", "Marketing Spend"]].mean()).abs())

Random sample difference:
R&D Spend          2354.7589
Marketing Spend          NaN
dtype: float64
Stratified sample difference:
R&D Spend          18171.272267
Marketing Spend             NaN
dtype: float64


Marketing Spend is closer to the population mean, while R&D Spend is farther from the population mean